window.BERAY_HEALTH_CATALOG={
  "Kalp ve Dolaşım": [
    "Koroner arter hastalığı",
    "Kalp yetmezliği",
    "Akut miyokard enfarktüsü",
    "Anjina pektoris",
    "Aritmi",
    "Kalp kapağı hastalıkları",
    "Aort darlığı",
    "Mitral kapak yetmezliği",
    "Atriyal fibrilasyon",
    "Supraventriküler taşikardi",
    "Ventriküler taşikardi",
    "Perikardit",
    "Miyokardit",
    "Kardiyomiyopati",
    "Hipertrofik kardiyomiyopati",
    "Dilate kardiyomiyopati",
    "Doğuştan kalp hastalıkları",
    "Pulmoner hipertansiyon",
    "Endokardit",
    "Kalp ritim bozuklukları",
    "Bradiaritmi",
    "Taşikardi",
    "Kalp kası hastalıkları",
    "Kalp kapak enfeksiyonları",
    "Kalp durması sonrası durumlar"
  ],
  "Damar Hastalıkları": [
    "Hipertansiyon",
    "Hipotansiyon",
    "Periferik arter hastalığı",
    "Karotis arter hastalığı",
    "Aort anevrizması",
    "Aort diseksiyonu",
    "Derin ven trombozu",
    "Pulmoner emboli",
    "Varis",
    "Kronik venöz yetmezlik",
    "Lenfödem",
    "Raynaud fenomeni",
    "Vaskülit",
    "Takayasu arteriti",
    "Dev hücreli arterit",
    "Poliarteritis nodoza",
    "Buerger hastalığı",
    "Tromboz",
    "Damar sertliği (ateroskleroz)",
    "Venöz tromboz"
  ],
  "Solunum Sistemi": [
    "Astım",
    "KOAH",
    "Kronik bronşit",
    "Amfizem",
    "Zatürre (pnömoni)",
    "Akut bronşit",
    "Tüberküloz",
    "Bronşektazi",
    "İnterstisyel akciğer hastalığı",
    "Pulmoner fibrozis",
    "Sarkoidoz",
    "Plevra hastalıkları",
    "Plevral efüzyon",
    "Pnömotoraks",
    "Uyku apnesi",
    "İnfluenza",
    "RSV enfeksiyonu",
    "Boğmaca",
    "Laringit",
    "Farenjit"
  ],
  "Sindirim Sistemi": [
    "Gastroözofageal reflü hastalığı",
    "Gastrit",
    "Peptik ülser",
    "Ülseratif kolit",
    "Crohn hastalığı",
    "İrritabl bağırsak sendromu",
    "Çölyak hastalığı",
    "Divertiküler hastalık",
    "Divertikülit",
    "Kabızlık",
    "Kronik ishal",
    "Gastroenterit",
    "Apandisit",
    "Bağırsak tıkanıklığı",
    "Hemoroid",
    "Anal fissür",
    "Karaciğer yağlanması",
    "Hepatit",
    "Siroz",
    "Pankreatit",
    "Safra taşı hastalığı",
    "Safra kesesi iltihabı",
    "Safra yolları hastalıkları",
    "Gastrointestinal kanama",
    "Mide kanseri"
  ],
  "Karaciğer ve Safra": [
    "Viral hepatit A",
    "Viral hepatit B",
    "Viral hepatit C",
    "Otoimmün hepatit",
    "Alkol ilişkili karaciğer hastalığı",
    "Alkolsüz yağlı karaciğer hastalığı",
    "Karaciğer sirozu",
    "Karaciğer yetmezliği",
    "Safra taşı",
    "Kolesistit",
    "Kolanjit",
    "Primer biliyer kolanjit",
    "Primer sklerozan kolanjit",
    "Hemokromatozis",
    "Wilson hastalığı",
    "Karaciğer kistleri",
    "Karaciğer apsesi",
    "Karaciğer tümörleri",
    "Safra kesesi polipleri",
    "Safra yolu tümörleri"
  ],
  "Sinir Sistemi": [
    "Migren",
    "Gerilim tipi baş ağrısı",
    "Epilepsi",
    "İnme",
    "Geçici iskemik atak",
    "Parkinson hastalığı",
    "Alzheimer hastalığı",
    "Multipl skleroz",
    "Periferik nöropati",
    "Trigeminal nevralji",
    "Menenjit",
    "Ensefalit",
    "ALS",
    "Huntington hastalığı",
    "Guillain-Barré sendromu",
    "Bell paralizisi",
    "Narkolepsi",
    "Hidrosefali",
    "Beyin anevrizması",
    "Sinir sıkışması",
    "Omurilik hastalıkları",
    "Demans",
    "Vasküler demans",
    "Huzursuz bacak sendromu"
  ],
  "Ruh Sağlığı ve Davranış": [
    "Depresif bozukluk",
    "Yaygın anksiyete bozukluğu",
    "Panik bozukluk",
    "Obsesif kompulsif bozukluk",
    "Travma sonrası stres bozukluğu",
    "Sosyal anksiyete bozukluğu",
    "Bipolar bozukluk",
    "Şizofreni",
    "Yeme bozuklukları",
    "Uyum bozukluğu",
    "Uyku bozuklukları",
    "Dikkat eksikliği hiperaktivite bozukluğu",
    "Otizm spektrum bozukluğu",
    "Somatik belirti bozukluğu",
    "Özgül fobiler",
    "Ayrılma kaygısı bozukluğu",
    "Bağımlılık bozuklukları",
    "Kişilik bozuklukları",
    "Tükenmişlik ile ilişkili sorunlar",
    "Stres ilişkili bozukluklar"
  ],
  "Göz ve Görme": [
    "Miyopi",
    "Hipermetropi",
    "Astigmatizma",
    "Presbiyopi",
    "Katarakt",
    "Glokom",
    "Makula dejenerasyonu",
    "Diyabetik retinopati",
    "Retina dekolmanı",
    "Konjonktivit",
    "Keratit",
    "Üveit",
    "Kuru göz hastalığı",
    "Göz kapağı iltihabı",
    "Şaşılık",
    "Ambliyopi",
    "Renk görme bozuklukları",
    "Optik nörit",
    "Retinitis pigmentosa",
    "Blefarit",
    "Göz enfeksiyonları"
  ],
  "Kulak Burun Boğaz": [
    "Otitis media",
    "Dış kulak yolu iltihabı",
    "Sinüzit",
    "Alerjik rinit",
    "Nazal polip",
    "Deviasyon",
    "Tonsillit",
    "Larenjit",
    "Ses teli nodülü",
    "İşitme kaybı",
    "Tinnitus",
    "Vertigo",
    "Meniere hastalığı",
    "Benign paroksismal pozisyonel vertigo",
    "Burun kanaması",
    "Kronik rinosinüzit",
    "Uyku ile ilişkili horlama",
    "Boğaz reflüsü",
    "Kulak zarı hastalıkları",
    "Östaki tüpü disfonksiyonu"
  ],
  "Ağız ve Diş": [
    "Diş çürüğü",
    "Diş eti iltihabı",
    "Periodontitis",
    "Diş apsesi",
    "Diş hassasiyeti",
    "Ağız kokusu",
    "Ağız kuruluğu",
    "Ağız yaraları",
    "Aft",
    "Temporomandibular eklem bozukluğu",
    "Diş sürme sorunları",
    "Gömülü diş",
    "Diş minesinde aşınma",
    "Diş gıcırdatma",
    "Dil hastalıkları",
    "Tükürük bezi hastalıkları",
    "Ağız mantar enfeksiyonu",
    "Çene kistleri",
    "Diş eti çekilmesi",
    "Ağız kanserleri"
  ],
  "Cilt ve Saç": [
    "Atopik dermatit",
    "Kontakt dermatit",
    "Seboreik dermatit",
    "Sedef hastalığı",
    "Akne",
    "Rozasea",
    "Ürtiker",
    "Egzama",
    "Mantar enfeksiyonları",
    "Uyuz",
    "Siğil",
    "Uçuk",
    "Zona",
    "Bakteriyel cilt enfeksiyonları",
    "Selülit",
    "Cilt apsesi",
    "Alopesi areata",
    "Androgenetik saç dökülmesi",
    "Vitiligo",
    "Melazma",
    "Benler",
    "Güneş yanığı",
    "Cilt kanserleri",
    "Basınç yarası"
  ],
  "Kas Eklem ve Kemik": [
    "Osteoartrit",
    "Romatoid artrit",
    "Osteoporoz",
    "Osteopeni",
    "Gut",
    "Ankilozan spondilit",
    "Psöriatik artrit",
    "Fibromiyalji",
    "Bel fıtığı",
    "Boyun fıtığı",
    "Skolyoz",
    "Kifoz",
    "Lordoz",
    "Tendinit",
    "Bursit",
    "Kas zorlanması",
    "Bağ yaralanmaları",
    "Menisküs yaralanması",
    "Donuk omuz",
    "Karpal tünel sendromu",
    "Lateral epikondilit",
    "Plantar fasiit",
    "Kemik enfeksiyonları",
    "Kemik tümörleri"
  ],
  "Böbrek ve İdrar Yolları": [
    "Böbrek taşı",
    "Kronik böbrek hastalığı",
    "Akut böbrek hasarı",
    "Böbrek yetmezliği",
    "Glomerülonefrit",
    "Pyelonefrit",
    "Sistit",
    "İdrar yolu enfeksiyonu",
    "İnkontinans",
    "Aşırı aktif mesane",
    "Prostatit",
    "Polikistik böbrek hastalığı",
    "Nefrotik sendrom",
    "Nefritik sendrom",
    "İdrar yolu taşları",
    "Böbrek kistleri",
    "Mesane iltihabı",
    "Mesane tümörleri",
    "Böbrek tümörleri",
    "İdrar akışı bozuklukları"
  ],
  "Endokrin ve Metabolizma": [
    "Tip 1 diyabet",
    "Tip 2 diyabet",
    "Gebelik diyabeti",
    "Hipoglisemi",
    "Metabolik sendrom",
    "İnsülin direnci",
    "Hipotiroidi",
    "Hipertiroidi",
    "Hashimoto tiroiditi",
    "Graves hastalığı",
    "Guatr",
    "Tiroid nodülü",
    "Cushing sendromu",
    "Addison hastalığı",
    "Akromegali",
    "Polikistik over sendromu",
    "Hiperlipidemi",
    "Obezite",
    "Vitamin D eksikliği",
    "Demir eksikliği",
    "B12 eksikliği",
    "Folik asit eksikliği",
    "Elektrolit bozuklukları"
  ],
  "Kan ve Bağışıklık": [
    "Demir eksikliği anemisi",
    "B12 eksikliği anemisi",
    "Aplastik anemi",
    "Hemolitik anemi",
    "Orak hücre hastalığı",
    "Talassemi",
    "Hemofili",
    "Von Willebrand hastalığı",
    "Lösemi",
    "Lenfoma",
    "Multipl miyelom",
    "Trombositopeni",
    "Nötropeni",
    "Pıhtılaşma bozuklukları",
    "Bağışıklık yetmezliği",
    "Otoimmün hastalıklar",
    "Lupus",
    "Sjögren sendromu",
    "İmmün trombositopeni",
    "Miyelodisplastik sendrom"
  ],
  "Enfeksiyon Hastalıkları": [
    "COVID-19",
    "Grip",
    "Nezle",
    "Kızamık",
    "Kızamıkçık",
    "Kabakulak",
    "Suçiçeği",
    "Boğmaca",
    "Rotavirüs enfeksiyonu",
    "Norovirüs enfeksiyonu",
    "Hepatit A",
    "Hepatit B",
    "Hepatit C",
    "HIV enfeksiyonu",
    "Tüberküloz",
    "Boğaz enfeksiyonları",
    "İdrar yolu enfeksiyonu",
    "Cilt enfeksiyonları",
    "Sepsis",
    "Sıtma",
    "Lyme hastalığı",
    "Deng humması",
    "Zika virüs enfeksiyonu",
    "Menenjit enfeksiyonları"
  ],
  "Kanserler": [
    "Meme kanseri",
    "Akciğer kanseri",
    "Prostat kanseri",
    "Kolorektal kanser",
    "Mide kanseri",
    "Karaciğer kanseri",
    "Pankreas kanseri",
    "Böbrek kanseri",
    "Mesane kanseri",
    "Tiroid kanseri",
    "Cilt kanseri",
    "Melanom",
    "Rahim ağzı kanseri",
    "Endometrium kanseri",
    "Yumurtalık kanseri",
    "Testis kanseri",
    "Baş ve boyun kanserleri",
    "Lösemi",
    "Lenfoma",
    "Miyelom",
    "Beyin tümörleri",
    "Kemik tümörleri",
    "Yumuşak doku sarkomları"
  ],
  "Kadın Sağlığı": [
    "Adet düzensizlikleri",
    "Ağrılı adet",
    "Endometriozis",
    "Adenomyozis",
    "Polikistik over sendromu",
    "Rahim miyomları",
    "Yumurtalık kistleri",
    "Pelvik inflamatuvar hastalık",
    "Vajinit",
    "Bakteriyel vajinozis",
    "Mantar vajiniti",
    "Menopoz belirtileri",
    "Erken menopoz",
    "Premenstrüel disforik bozukluk",
    "Doğum sonrası depresyon",
    "Gebelikle ilişkili hipertansiyon",
    "Ektopik gebelik",
    "Gebelikte anemi",
    "İdrar kaçırma",
    "Pelvik taban bozuklukları"
  ],
  "Erkek Sağlığı": [
    "Benign prostat hiperplazisi",
    "Prostatit",
    "Prostat kanseri",
    "Erektil disfonksiyon",
    "Erken boşalma",
    "Testis torsiyonu",
    "Varikosel",
    "Hidrosel",
    "Epididimit",
    "Orşit",
    "Testis kanseri",
    "Erkek infertilitesi",
    "Hipogonadizm",
    "Androjen eksikliği",
    "Fimozis",
    "Parafimozis",
    "Sperm bozuklukları",
    "Kasık fıtığı",
    "Penis hastalıkları",
    "Erkek üriner sistem hastalıkları"
  ],
  "Çocuk ve Ergen Sağlığı": [
    "Çocukluk çağı astımı",
    "Çocukluk çağı egzaması",
    "Bronşiolit",
    "Krup",
    "Çocukluk çağı zatürresi",
    "Çocukluk çağı gastroenteriti",
    "Orta kulak iltihabı",
    "Büyüme geriliği",
    "Gelişimsel gecikme",
    "Dikkat eksikliği hiperaktivite bozukluğu",
    "Otizm spektrum bozukluğu",
    "Öğrenme güçlüğü",
    "Skolyoz",
    "Çocukluk çağı diyabeti",
    "Kawasaki hastalığı",
    "Büyüme hormonu bozuklukları",
    "Doğuştan kalp hastalıkları",
    "Ergenlik bozuklukları",
    "Çocukluk çağı anemileri",
    "Çocukluk çağı alerjileri",
    "Beslenme yetersizlikleri"
  ],
  "Gebelik ve Doğum": [
    "Gebelikte bulantı ve kusma",
    "Gebelikte reflü",
    "Gebelikte anemi",
    "Gebelikte diyabet",
    "Preeklampsi",
    "Eklampsi",
    "Plasenta previa",
    "Plasental abrupsiyon",
    "Erken doğum",
    "Doğum sonrası kanama",
    "Doğum sonrası enfeksiyonlar",
    "Lohusalık sorunları",
    "Ektopik gebelik",
    "Mol gebelik",
    "Düşük",
    "Fetal büyüme kısıtlılığı",
    "Gebelikte kolestaz",
    "Gebelikte tiroid bozuklukları",
    "Gebelikte hipertansiyon",
    "Doğum sonrası depresyon"
  ],
  "Genetik ve Doğuştan Durumlar": [
    "Down sendromu",
    "Turner sendromu",
    "Klinefelter sendromu",
    "Marfan sendromu",
    "Ehlers-Danlos sendromları",
    "Kistik fibrozis",
    "Fenilketonüri",
    "Orak hücre hastalığı",
    "Hemokromatozis",
    "Talasemi",
    "Fragile X sendromu",
    "Huntington hastalığı",
    "Hemofili A",
    "Hemofili B",
    "Spinal müsküler atrofi",
    "Duchenne kas distrofisi",
    "Gaucher hastalığı",
    "Williams sendromu",
    "Nörofibromatozis",
    "Konjenital kalp anomalileri"
  ],
  "Üreme ve Cinsel Sağlık": [
    "İnfertilite",
    "Cinsel işlev bozuklukları",
    "Erektil disfonksiyon",
    "Vajinal kuruluk",
    "Pelvik ağrı",
    "Adet bozuklukları",
    "Endometriozis",
    "Polikistik over sendromu",
    "Cinsel yolla bulaşan enfeksiyonlar",
    "Genital herpes",
    "HPV enfeksiyonu",
    "Klamidya enfeksiyonu",
    "Gonore",
    "Sifiliz",
    "Trikomoniyaz",
    "Hepatit B enfeksiyonu",
    "HIV enfeksiyonu",
    "Üreme sistemi enfeksiyonları",
    "Doğurganlık sorunları",
    "Pelvik taban bozuklukları"
  ],
  "Yaşlanma ve İleri Yaş": [
    "Osteoporoz",
    "Katarakt",
    "Glokom",
    "Demans",
    "Alzheimer hastalığı",
    "Parkinson hastalığı",
    "İnme",
    "Kalp yetmezliği",
    "Hipertansiyon",
    "Tip 2 diyabet",
    "İşitme kaybı",
    "Sarkopeni",
    "Düşme riski ile ilişkili durumlar",
    "İdrar kaçırma",
    "Bilişsel bozukluk",
    "Kronik böbrek hastalığı",
    "Kronik akciğer hastalığı",
    "Makula dejenerasyonu",
    "Eklem hastalıkları",
    "Beslenme yetersizlikleri"
  ],
  "Uyku Sağlığı": [
    "Uykusuzluk",
    "Obstrüktif uyku apnesi",
    "Merkezi uyku apnesi",
    "Huzursuz bacak sendromu",
    "Narkolepsi",
    "Parasomniler",
    "Sirkadiyen ritim uyku bozuklukları",
    "Hipersomni",
    "Uyku terörü",
    "Uyurgezerlik",
    "Kabus bozukluğu",
    "Gece yeme sendromu",
    "Vardiyalı çalışmaya bağlı uyku sorunu",
    "Jet lag",
    "Uyku ile ilişkili hareket bozuklukları",
    "Bruksizm ile ilişkili uyku sorunları",
    "Çocukluk çağında uyku bozuklukları",
    "Ergenlikte uyku sorunları",
    "Yaşlılarda uyku sorunları",
    "Kronik uyku yoksunluğu"
  ],
  "Alerji ve Bağışıklık": [
    "Mevsimsel alerjik rinit",
    "Ev tozu akarı alerjisi",
    "Polen alerjisi",
    "Kedi köpeğe alerji",
    "Gıda alerjisi",
    "İlaç alerjisi",
    "Böcek sokması alerjisi",
    "Lateks alerjisi",
    "Kontakt dermatit",
    "Ürtiker",
    "Anjiyoödem",
    "Anafilaksi",
    "Alerjik astım",
    "Atopik dermatit",
    "Alerjik konjonktivit",
    "Eozinofilik özofajit",
    "Bağışıklık yetmezliği",
    "Otoimmün tiroid hastalıkları",
    "Lupus",
    "Romatoid artrit"
  ],
  "Gözden Kaçmaması Gereken Belirtiler": [
    "Ani görme kaybı",
    "Ani konuşma bozukluğu",
    "Yeni başlayan yüz-kol güçsüzlüğü",
    "Şiddetli göğüs ağrısı",
    "Nefes almada belirgin güçlük",
    "Bayılma",
    "Şiddetli ve ani baş ağrısı",
    "Ciddi kanama",
    "Bilinç değişikliği",
    "Şiddetli alerjik reaksiyon",
    "Ciddi kafa travması",
    "Şiddetli karın ağrısı",
    "Mavi/ morarma",
    "Yeni başlayan nöbet",
    "Şiddetli susuzluk ve bilinç bulanıklığı",
    "Hızla kötüleşen genel durum"
  ]
};
window.BERAY_HEALTH_CATALOG_TOTAL=521;
